/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./src/components/user/ActionBar.vue')['default']
    BonusDiagram: typeof import('./src/components/user/BonusDiagram.vue')['default']
    CommonCard: typeof import('./src/components/user/CommonCard.vue')['default']
    DynamicCard: typeof import('./src/components/dynamic/DynamicCard.vue')['default']
    LinkCard: typeof import('./src/components/dynamic/LinkCard.vue')['default']
    RoleTag: typeof import('./src/components/RoleTag.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabbarComponent: typeof import('./src/components/tabbar/TabbarComponent.vue')['default']
    UserCard: typeof import('./src/components/UserCard.vue')['default']
    VanActionBarButton: typeof import('vant/es')['ActionBarButton']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanImage: typeof import('vant/es')['Image']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
